### ISSUE TITLE
How to use it in browser?

### ISSUE THREAD

**Issue by petervojtek** [mWater/offline-leaflet-map#14]
Hello,

I appreciate this library, however I am not very successful using it in a browser (actually in [ionic framework](http://ionicframework.com/)) [no nodejs].

I managed to export the `offlinemap.js` via Browserify, but I still face `OfflineLayer is not defined`. 
I am also not sure which of the .coffee files are really necessary to use the library, so far I only included `offlinemap.browserified.js` in my html.

Honestly, I believe this library would have much broader audience if you rather use plain JS instead of coffeescript. (I have nothing against coffeescript and done few projects in it, but currently it is rather a obstacle for me than a help). 

All the best,
Peter

**Comment by grassick** [comment]
No coffeescript is necessary to use the library... just include `dist/offlinemap.js` and all should be well.

**Comment by petervojtek** [comment]
Hi grassick,
thank you for quick reply.
My apologies, I had a typo in my <script> include line.

I managed to launch and it plays well even with [angular-leaflet-directive](https://github.com/tombatossals/angular-leaflet-directive).

P.

**Comment by grassick** [comment]
Great! Enjoy!
