### ISSUE TITLE
A lot of incorrect image downloads

### ISSUE THREAD

**Issue by ultimate-tester** [mWater/offline-leaflet-map#17]
Sorry for creating another issue but I would like to address one issue at a time.
So the problem is that the algorithm for downloading tiles generate a lot of false URLs.
Earlier I spoke about a CORS header error, but that is another problem caused by the invalid image URL (only a valid image URL contains the CORS header. The 404 page does not include the CORS header). The following screenshots shows the failed downloads:

![Image tile failures](https://cdn.pbrd.co/images/lBsZdipw1.png)

You see only 1% of all tiles that gets download is a valid image, the rest is not found (aka 404).
I feel like there's an error in the algorithm causing a lot of invalid image URLs.

**Comment by sanastasiou** [comment]
I can concur here.  There is something way off with the images. I am trying to analyze this thing now, cause I really need this offline capability for my site.

**Comment by grassick** [comment]
How right you are... I'm looking into this now!

**Comment by grassick** [comment]
@broncha Can you look into this once you're done with the response comparer? I didn't personally write this code, but it looks like there is a bug in the calculating of the slippy tile map coordinates in some cases. At least, when zoomed in near my house in Montreal (45.536, -73.619) it fails. You can reproduce in the app by using the Android version and downloading map offline and choosing yes to tiles, but there's maybe a more obvious bug in the download?

When I tried it, it was trying to download https://b.tile.openstreetmap.org/13/9679/11715.png which doesn't exist. My house is actually near https://b.tile.openstreetmap.org/13/2418/2929.png which is a factor of 4 off.

**Comment by broncha** [comment]
@grassick I tried this one in browser with \

```
mapquestUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
subDomains = ['a','b', 'c']
```

I dont see any 404s.

In the app, I keep getting `GET_STATUS_ERROR`, not much info in logcat.

**Comment by grassick** [comment]
Well, the x and y coordinates are sometimes but not always way off... I'd enable it for the browser (it's turned off) and then go to the place in Montreal at zoom level 12. That should trigger it. If not, please have a look through the algorithm for calculating the tile x+y values, as there is definitely a logic bug.

**Comment by broncha** [comment]
Cracked this today!!
There was a confusion, as the repo downloaded from npm is not same as the github master. And the version reported in npm is also not listed in tags in github!

The code while installing from npm and github master is not the same! This is the specific line

In Master

```
    map = @_map
    startingZoom = map.getZoom()
    bounds = map.getPixelBounds()
    tileSize = @getTileSize()
```
From npm

```
    map = @_map
    startingZoom = map.getZoom()
    bounds = map.getPixelBounds()
    # Handle both Leaflet 0.7 (_getTileSize) and 1.0
    tileSize = if @_getTileSize then @_getTileSize() else @getTileSize().x
```

Thats one of the issue, and the main issue causing the 404s is `getTileUrl`.
Turns out leaflet never cared about the zoomlevel passed.
From Leaflet

```
getTileUrl: function (coords) {
    var data = {
    	r: L.Browser.retina ? '@2x' : '',
    	s: this._getSubdomain(coords),
    	x: coords.x,
    	y: coords.y,
    	z: this._getZoomForUrl()
    };
    if (this._map && !this._map.options.crs.infinite) {
    	var invertedY = this._globalTileRange.max.y - coords.y;
    	if (this.options.tms) {
    		data['y'] = invertedY;
    	}
    	data['-y'] = invertedY;
    }

    return L.Util.template(this._url, L.extend(data, this.options));
}
```

I am going to override the `getTileUrl` in OffLineLayer and add the getTileSize fix.
