### ISSUE TITLE
tilecachingprogressdone not called when tiles downloaded

### ISSUE THREAD

**Issue by grassick** [mWater/offline-leaflet-map#32]
I was in the process of reworking the cache progress control, and I noticed that if there are any actual tiles to download, then the tilecachingprogressdone event is not fired at the end. Do you have any idea why this might be? I had a look at it and  nothing obvious jumped out, but I don't really know the code particularly well.

**Comment by grassick** [comment]
I've put a hack in apps/mwater-app/app/js/components/CacheProgressControl.tsx to workaround it for now.

**Comment by broncha** [comment]
This issue apparantly had been there since a decade
https://github.com/mWater/offline-leaflet-map/commit/69cc09a447a6d57e0d8b6971d79730f6e4a534d5#diff-a08937adc809f5f170d5dc48eea9a9847c3ed71302c140654c47247e73274a64
